# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-04 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Inst', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='division',
            name='curso',
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Inst.Curso'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nivel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Inst.Nivel'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestion_Inst.Division'),
        ),
    ]
